### ISSUE TITLE
Icon for The Book of Unwritten Tales (and The Critter Chronicles) (Steam)

### ISSUE THREAD

**Issue by ChuckDaniels87** [numixproject/numix-icon-theme-circle#1308]
Game: __The Book of Unwritten Tales__
AppID: __215160__

Game: __The Book of Unwritten Tales: The Critter Chronicles__
AppID: __221830__

Icon:
![the book of unwritten tales_1](https://cloud.githubusercontent.com/assets/8478202/5094923/47bd0360-6f65-11e4-97e2-ba81d03ad62b.png)

I'll try to do it this week if I get some ideas.

**Comment by MrTimscampi** [comment]
Proposal for The Book of Unwritten Tale:
![steam_icon_215160](https://cloud.githubusercontent.com/assets/1087450/11122239/9b1e1412-895a-11e5-967d-f19645cf7608.png)
**SVG: ** https://dl.dropboxusercontent.com/u/40932393/steam_icon_215160.svg

It's one of the main characters of the game.
It may lack a shadow on the pinkinsh body, but I'm not sure.

**Comment by ChuckDaniels87** [comment]
There are two icons (Original Game, Critter Chronicles). That one fit Critter Chronicles very well but you should change background color. Try not using fullscreen symbol if you can.

I'd thought in something similar for Critter Chronicles. Additionally, Wilbur's face would be nice for the original game.

**Comment by ChuckDaniels87** [comment]
You can try something like this:

![steam_icon_215160](https://cloud.githubusercontent.com/assets/8478202/11130612/df8f7a64-897d-11e5-8cd9-0304af17967f.png)

**Comment by MrTimscampi** [comment]
Here's a corrected one for Critter Chronicles:
![steam_icon_221830](https://cloud.githubusercontent.com/assets/1087450/11130738/ed473134-8986-11e5-84d0-f97dac81b003.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_221830.svg

For the circle, I chose the complimentary color of the one I used for the body, so that it has good contrast and is coherent.

**Comment by MrTimscampi** [comment]
Here's my shot at a Wilbur icon for the base game:
![steam_icon_215160](https://cloud.githubusercontent.com/assets/1087450/11132987/7cd7d040-8993-11e5-9d5b-965dcf6e8931.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_215160.svg

**Comment by ChuckDaniels87** [comment]
This is just personal opinion: what about a more vivid green background for Critter? And a vivid red for Wilbur's background ?

**Comment by MrTimscampi** [comment]
Here's what they would look like.

![steam_icon_221830-v2](https://cloud.githubusercontent.com/assets/1087450/11134302/dbb86dba-899b-11e5-9738-86ea62609f72.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_221830-v2.svg

![steam_icon_215160-v2](https://cloud.githubusercontent.com/assets/1087450/11134318/fa225fd6-899b-11e5-9976-bf83b25e7152.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_215160-v2.svg

The original colors were automatically-calculated complimentary colors of the skins of the character. I tried making the second version not too jarring.

**Comment by Foggalong** [comment]
I'll be honest, I definitely preferred the the blue background for Wilbur's icon.

**Comment by ChuckDaniels87** [comment]
Yeah, absolutely. I prefer your first design. What about a brighter green for Creeper?
![steam_icon_221830-v2](https://cloud.githubusercontent.com/assets/8478202/11145943/e40921ec-8a01-11e5-99a1-60b480a1d2b0.png)
_I've used same colour but L:170-160 in HSL palette._

**Comment by Foggalong** [comment]
I think that's a bit too bright, though none of the greens so far have been that good

**Comment by Eleuin** [comment]
yeah, just a bit less saturated maybe

**Comment by MrTimscampi** [comment]
I liked the blue Wilbur icon more as well. I can't find a red that doesn't look bad with his skin while still giving enough contrast to actually be able to see the symbol.
I might re-color his eyes, because they look kind of like he's sick, after taking a few days off from looking the design.

For Critter's, I can't seem to find a good green, but, as with Wilbur's, after a few days without looking at it, I definitely see what you guys were saying. I'll keep looking for a more suitable color.

Will edit this or reply when I found something.

**Comment by Foggalong** [comment]
Submit away :)

**Comment by ChuckDaniels87** [comment]
Really nice job. :+1:
