### ISSUE TITLE
Icon for Bioshock Infinite (Steam)

### ISSUE THREAD

**Issue by cjcou** [numixproject/numix-icon-theme-circle#1371]
Name: Bioshock Infinite
AppID: 8870
Icon: http://fc01.deviantart.net/fs71/f/2013/085/c/4/bioshock_infinite_icon_for_obly_tile_by_enigmaxg2-d5zesqw.png
Notes: Game set in a dystopian 1920's US themed world.

**Comment by Eleuin** [comment]
i see this pull request has been open for a while now, so what im going to do is propose an alternate design. instead of this highly complex icon that will not complly with standards, i suggest we go with a skyhook design as its a more icon weapon from the series and is a lot more doable. something along the lines of this
![bioshock_infinite___simple_windows_metro_dock_icon_by_geliras-d5zs9te png](https://cloud.githubusercontent.com/assets/5553828/7970903/20323f0a-0a0f-11e5-863e-ac9524c9e0d5.jpg)

**Comment by FoxyAntho** [comment]
Why not something like this :

![infinite](https://cloud.githubusercontent.com/assets/7000625/8508316/c811fb7e-226b-11e5-9569-1ac1b0c99f45.png)

I used this as a reference : http://vignette1.wikia.nocookie.net/bioshock/images/5/57/BioShock_Infinite_Clean_Logo.png/revision/latest?cb=20110607033449

I have the vector if you are interested :smile: 

edit: little problem in alignment!

**Comment by Eleuin** [comment]
well, i guess i don't have to get started on this anymore xD
only complain is with the stripes meshing with the blue. gonna sound really weird, but try pulling one upper corner up past and behind the blue edge, this makes the edges a lot smoother without altering the look.

**Comment by wa4557** [comment]
The symbol is probably too big as well

**Comment by Eleuin** [comment]
@FoxyAntho at this point, its just getting the symbol shrunk, everything aligned to the pixel grid (view->page grid), and the blue edge fixed.

**Comment by FoxyAntho** [comment]
@Eleuin Thanks for the advices !
There it is :
![infinite](https://cloud.githubusercontent.com/assets/7000625/8508682/ebe56226-2279-11e5-9095-52f934b96aa6.png)

Vector file : http://foxyantho.fr/micons/infinite.svg

**Comment by Eleuin** [comment]
@FoxyAntho i looked over the svg. I really love where this is headed, and i have no doubt @Foggalong is going to love this too, there are just a few things that need to be done to bring this closer to the guidelines. First off, all the strokes need to be converted to paths (this really isn't terribly difficult, its just path->stroke to path). The stripes should also be aligned to the pixel grid, seeing as how they are the only objects in the icon with horizontal and vertical lines (Show that page grid, allows you to actually see where the pixel boundaries are :smile: ). Finally, I noticed that the symbol shadow is not really up to spec, just needs to be moved 1 pixel down and to the right.

**Comment by FoxyAntho** [comment]
@Eleuin Okay, I now know that, maybe for a next time :smile: It could also be interesting to add the [Guidelines](https://github.com/numixproject/numix-wiki/wiki/Guidelines) to the Readme. I don't had seen it the first time.
The shadow is correctly positioned, it's because of his form it looks strange, 2px move is too much so I guess it can't be helped.

Why converting strokes to paths ? Performance, compatibility ? I though it was more easy to edit it later if we need to.

**Comment by Eleuin** [comment]
@FoxyAntho its not so much a 2px move, its more of 2x 1px move in seperate dimensions, so while the x value is more or less right (its a bit off, with the bottom shadow node being at x=24.999), the shadow still needs to be brought down by 0.745, along with the stripe nodes being brought to the pixel grid so their positions are a whole number. About the strokes, they are just rather hard to deal with and a lot of the tools use paths instead of strokes. I wouldn't at all doubt it if they have caused troubles in the past as well. Your work isn't bad at all, in fact i personally think the design work is rather sexy, it just needs some refinement to get it closer to guidelines :stuck_out_tongue:

**Comment by Foggalong** [comment]
That is gorgeous.

**Comment by Foggalong** [comment]
Seems @FoxyAntho has disappeared. I downloaded the vector file and modified it to bring it a bit closer to the guidelines :)
