### ISSUE TITLE
Using circle icons for just apps.

### ISSUE THREAD

**Issue by agauniyal** [numixproject/numix-icon-theme-circle#1380]
Is there a way I could use numix icon theme (circle) just for apps so that it neglects any folder , settings , unity panel icons? My elementary os freya breaks on top panel when using these icons but I want to preserve those circular app icons too. Thanks :smile:

**Comment by bil-elmoussaoui** [comment]
is it posssible to use only 48x48 icons?

**Comment by Foggalong** [comment]
I'm not sure what you mean? We use 48x48 as standard size for all our app icons

**Comment by bil-elmoussaoui** [comment]
the small icons looks ugly in elementary os 0.3 (some weird black borders); and i would like to use only the 48X48 for my applications and use the defaults icons of elementary for small sizes?

**Comment by Foggalong** [comment]
Oh right. In which case just follow the instructions in the comment above.

**Comment by bil-elmoussaoui** [comment]
Thank you @Foggalong ; i still have a question; is it possible to use only the Numix Folders? with the Numix-Circle Icons? if not could you make it possible; as you're supporting 6 styles; some people would like to use only the folders from Numix and keep the original icons or use an other theme! 
Thank you very much! if you can could you help me to do it? i tried by removing all other folders in Numix and only keeping the places folder but its not working? i did regenerate the theme cache;)
Thank you again!

**Comment by Foggalong** [comment]
Just to clarify what you mean:

* You want to use the Numix Circle icons for applications
* You want to use the Numix Folders icons for folders
* You want to use another theme (I'll use elementary as the example) for all the other icons, such as mimetypes and status icons.

I know you say "some people", but you're honestly the only person I've seen ask for this as it's a very specialized request :P For that reason this definitely isn't something we'd ever officially implement. Regardless, this is how you would go about doing it. Based on your comment above I'll assume you're using an Ubuntu-based distro like elementary.

1. Install [Numix Circle](https://github.com/numixproject/numix-icon-theme-circle) and [Numix Base](https://github.com/numixproject/numix-icon-theme).

2. Open the Numix Base icon directory and delete all the folders, leaving only `index.theme` & `icon-theme.cache`

3. Download [Numix Folders](https://github.com/numixproject/numix-folders) and run the script to pick your style of choice. This will then copy your folder icons into the Base directory.

4. Open the file called `index.theme` from the Numix Base directory in the text editor of your choice, delete everything and replace it with the text shown below (replacing `elementary` with the icon theme you wish to use for everything else)

5. Open your settings manager, navigate to the appearance section, and pick "Numix Circle" as your icon theme in the relevant section.

6. Log out and log back in again to make sure it applies all across your desktop.


##### index.theme replacement
Paste this into the Numix Base `index.theme` file (see step 5)

```bash
[Icon Theme]
Name=Numix

Comment=Icon theme from Numix Project

Inherits=elementary,hicolor

Example=folder

Directories=16x16/actions,16x16/places,22x22/actions,22x22/places,24x24/actions,24x24/places,32x32/actions,32x32/places,48x48/actions,48x48/places,64x64/actions,64x64/places,96x96/actions,96x96/places,128x128/actions,128x128/places,256x256/actions,256x256/places,scalable/places

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[22x22/actions]
Size=22
Context=Actions
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[24x24/actions]
Size=24
Context=Actions
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[32x32/actions]
Size=32
Context=Actions
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[48x48/actions]
Size=48
Context=Actions
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[64x64/actions]
Size=64
Context=Actions
Type=Fixed

[64x64/places]
Size=64
Context=Places
Type=Fixed

[96x96/actions]
Size=96
Context=Places
Type=Fixed

[96x96/places]
Size=96
Context=Places
Type=Fixed

[128x128/actions]
Size=128
Context=Actions
Type=Fixed

[128x128/places]
Size=128
Context=Places
Type=Fixed

[256x256/actions]
Size=256
MinSize=56
MaxSize=512
Context=Actions
Type=Scalable

[256x256/places]
Size=256
MinSize=56
MaxSize=512
Context=Places
Type=Scalable

[scalable/places]
Size=16
MinSize=16
MaxSize=256
Context=Places
Type=Scalable
```

Hope this solves your problem!

**Comment by bil-elmoussaoui** [comment]
Thank you so much! i forgot to modify the index.theme ;) and i want to use the elementary theme as its only in beta i'm waiting for the stable release so i can ask you to symlink the new icons ;) so i can use the Numix Base theme again!

**Comment by Foggalong** [comment]
Out of curiosity, what's the problem you're having with just using the base theme on it's own?

**Comment by bil-elmoussaoui** [comment]
I have two many problems:
- i prefer the white panel icon its fits better with Elementary theme and the wingpanel is transparent so with grey icons (Numix base one) are not looking very nice to me;
Using Numix Base
![capture du 2015-02-24 15 10 18](https://cloud.githubusercontent.com/assets/7660997/6350828/5e554b68-bc37-11e4-8c0d-43a6f0418097.png)

Using Elementary theme 
![capture du 2015-02-24 15 10 59](https://cloud.githubusercontent.com/assets/7660997/6350831/6260269c-bc37-11e4-8c3d-43eb7d9f7d3e.png)

- Need some symlinks in geary, maya,settings,pantheon files, 
Settings
![capture du 2015-02-24 15 12 07](https://cloud.githubusercontent.com/assets/7660997/6350846/850ff67c-bc37-11e4-8a89-a21eb13bd6ab.png)
Geary
![capture du 2015-02-24 15 12 59](https://cloud.githubusercontent.com/assets/7660997/6350913/ab661da6-bc37-11e4-9279-7dceeeaddd2b.png)
![capture du 2015-02-24 15 13 11](https://cloud.githubusercontent.com/assets/7660997/6350914/ab66579e-bc37-11e4-9e68-5fe655071221.png)
The language indicator (I already reported this to Numix Base theme)

![capture du 2015-02-24 15 15 13](https://cloud.githubusercontent.com/assets/7660997/6350972/f195adaa-bc37-11e4-8836-4c0904b6b99a.png)

Social accounts ( i dont know why the icons are on the Numix-Circle? i ve tried to use numix-circle with Elementary icons and the icons didnt change?) 
![capture du 2015-02-24 15 16 21](https://cloud.githubusercontent.com/assets/7660997/6350988/1fa31c14-bc38-11e4-9198-bd73218a48ec.png)

Very bad symlink with Elementary icons(not Numix is fault i know..)  In FeedReader
With Numix
![capture du 2015-02-24 15 17 46](https://cloud.githubusercontent.com/assets/7660997/6351019/6abf24a4-bc38-11e4-8ad0-a47babcb8f30.png)
Without
![capture du 2015-02-24 15 18 07](https://cloud.githubusercontent.com/assets/7660997/6351018/6abe9fac-bc38-11e4-804d-65a0831e30ed.png)

And there's more ;) and i cant use numix-gtk-theme as the last version (in the ppa) is not really the most recent one; as its not really working at all in Ferya 0.2 beta (GTK 3.14 problems)
so i'm still waiting :D

**Comment by Foggalong** [comment]
Just a response :)

1. The icons are a colour white (#f9f9f9) so I assume you're on about dropbox? That looks like a bug to me so feel free to report it. Same with the language icon - once folders are done and I'm back working on base that should be fixed asap.

2. We don't actively go searching for icons we've not yet covered, so the only way we find out about missing icons is if someone reports them to us :(

3. Apart form the Microsoft one (which needs to be reported!) those social account icons are actually Numix icons. For whatever reason (I don't know, I wasn't there) it was decided that they shouldn't have the same design as the app

4. The FeedReader is possibly a doggy symlink on our end - any idea what the icon name is?

5. @satya164 is the one to ask about problems with the GTK theme, he should be able to help you out with that :)

**Comment by bil-elmoussaoui** [comment]
1 - I will report this asap ;) little busy with studies.
2 - I will try to report all the icons once the elementary stable is released (to avoid symlinking some icons that wont be used later)
3 - I will report the microsoft one ;) 
4 - for the the star icon i guess its a elementary OS bug : the icon is help-about.svg? i dont know why putting a star icon for a help icon 
5 - I will report some problems with the gtk theme once i got the last official update so i can try it :D 
Thank you for you answer!

**Comment by Foggalong** [comment]
1. Not a problem! Hope studies go well :)
2. Good thinking
3. Thanks!
4. Ah, in which case it's probably a bug with elementary then.
5. Goodo!

Not a problem, here to help :)

**Comment by dirtydancing** [comment]
Wow, there are a lot of questions and issues in here! I would like to offer some thoughts on one aspect: the panel icons and in particular the colours white and light grey. 

You added two panel screenshots, and I am assuming (please correct me if I am wrong) that you are using the default elementary GTK theme both times. In the first screenshot, you are using Numix base icon theme, and in the second screenshot you are using the default elementary icon theme:

elementary GTK theme & Numix base icon theme
![5e554b68-bc37-11e4-8c0d-43a6f0418097](https://cloud.githubusercontent.com/assets/7164227/6359629/dd272e24-bc74-11e4-8530-78ae7e0930cb.png)

elementary GTK theme & elementary icon theme
![6260269c-bc37-11e4-8c3d-43eb7d9f7d3e](https://cloud.githubusercontent.com/assets/7164227/6359647/eb03b62a-bc74-11e4-9b15-3890421da545.png)

About the white colour: As far as I can tell, with Numix base the colour in the panel will be light grey, not white. And the Numix base panel icons in your first screenshot are actually light grey (e.g. E-Mail, network, sound, and also dropbox, which I do not believe is a bug, but so on purpose, happy to stand corrected, though). What likely causes the confusion is that there are also some white status icons in the first screenshot. This leads me to the conclusion that these are actually not Numix base status icons (possibly they come from elementary icon theme?).

In the special case of the language indicators: these do not exist in Numix base (iirc only for En) so far, because each one would need to be created on its own, and there are loads and loads of these. Or has this changed?

It might also be noteworthy that elementary GTK theme is exclusively supporting the elementary icons, so you might run into inconsistencies with the white/grey when you are using Numix icon theme. Just today, I filed a bug report againg elementary GTK theme in combination with Numix icon theme, and this resulted in a "Won't Fix" status (in this case about the battery status icon, a special case in itself, which is not in your screenshot, cf. https://bugs.launchpad.net/egtk/+bug/1425133 cf. also this section in a long long long bug thread https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-74034696).

Hope this helps somewhat. And to me, this also shows that it makes sense to address these issues one by one, as I have addressed only a fraction of what you mentioned :-)

**Comment by Foggalong** [comment]
@dirtydancing the Numix status icons are white, not grey. The colour is [#f9f9f9](http://www.color-hex.com/color/f9f9f9)

**Comment by dirtydancing** [comment]
@Foggalong I see. Not going to argue with you about the colours of the icons that you are designing :-)

I am just wondering: I thought white is <a href="http://www.color-hex.com/color/ffffff">#ffffff</a>, so <a href="http://www.color-hex.com/color/f9f9f9">#f9f9f9</a> would be a light grey, wouldn't it? Anyways, the Numix status icons "look" light grey e.g. on the panel in Ubuntu, Xubuntu and also in elementary OS Freya Beta, whereas the elementary status icons "look" white in elementary OS Freya Beta.

**Comment by Foggalong** [comment]
If I've understood correctly, #ffffff isn't the only white just as #ff0000 isn't the only red

**Comment by dirtydancing** [comment]
Haha, as I said, not arguing with you on the colours/colour namens that you are using. So, to differentiate between the colours of the status icons in Numix icon theme and in elementary icon theme, should we say "Numix white" and "elementary white"? :-)

**Comment by agauniyal** [comment]
@bil-elmoussaoui , how did you manage to get dropbox on that panel :open_mouth:

**Comment by Foggalong** [comment]
@dirtydancing Being as they're both white that would probably make the most sense. Though if you want to be technical I think elementary is #ffffff and Numix is #f9f9f9

**Comment by dirtydancing** [comment]
@Foggalong Agreed, sounds both good to me. Actually, I have come to like the name Numix white :-) But of course, the #f9f9f9 would be more precise (and possibly less confusing for others).

And just as a comment on the colour itself: I really like the Numix white! For me, this works very well.

**Comment by dirtydancing** [comment]
@foggalong This leads to my next colour question: Are you saying that Numix white <a href="http://www.color-hex.com/color/f9f9f9">#f9f9f9</a> is actually used in the panel? Because e.g. for `indicator-messages.svg` in Numix base `22x22/status` Inkscape is showing <a href="http://www.color-hex.com/color/dedede">#dedede</a>. And the same <a href="http://www.color-hex.com/color/dedede">#dedede</a> is showing in GIMP when I click on the message indicator icon on my panel in Ubuntu 14.10. Or is this possibly influenced by the respective GTK theme?

Inkscape screenshot:

![inkscape_222](https://cloud.githubusercontent.com/assets/7164227/6396429/ab78563a-bdde-11e4-9774-5c5b7e8c7637.png)

GIMP screenshot:

![gimp_222](https://cloud.githubusercontent.com/assets/7164227/6396443/cdfe0cea-bdde-11e4-9926-eccc81ae1980.png)

**Comment by Foggalong** [comment]
Well shoot. I think I might just have been schooled in my icon design. #dedede would indeed be the right colour, and it is indeed grey. Ignore **everything** I said above. There is a Numix white which is #f9f9f9, but it's not the colour used in the panel :P

**Comment by Foggalong** [comment]
Moved the root of this issue to the one linked above being as this question is now answered and that the original problem lies in base.

**Comment by bil-elmoussaoui** [comment]
@agauniyal you can contact me at my email adress bil.elmoussaoui@gmail.com ;)
