### ISSUE TITLE
Update the ppa

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#1423]
Hello, 
we have seen a lot of icons who have been merged; but we havent seen an update(PPA).. since the last month :( 
Hope to the see the new icons asap;
Thanks!

**Comment by palob** [comment]
In commit https://github.com/numixproject/numix-icon-theme-circle/commit/955503f0be8cc716f19e6dc61a69dd2a35666ab0 among other things I added symlinks for Battle of Wesnoth and changed the base svgs the symlinks refer to from *wesnoth-1.10_editor-icon.svg* and *wesnoth-1.10-icon.svg* to *wesnoth-editor.svg* and *wesnoth.svg*.

Some time ago, when I pasted the updated iconset into the folder containing the pre-commit set I would run into a state with only symlinks pointing to each other without an actual svg. That occured since the overwriting is done in sequence.
So in order to avoid this you'd have to delete the old wesnoth icons before pasting the new ones.

Is this relevant for ppa users? Should I do a PR for restoring the old symlink-svg relation?

**Comment by Foggalong** [comment]
I don't think that should be causing any problems. @satya164, @PaoloRotolo ?

**Comment by PaoloRotolo** [comment]
Actually we can't upload new versions of Circle on our PPA due of a Launchpad bug.
We're getting in touch with Canonical engineers to fix the issue as soon as possible.

**Comment by bil-elmoussaoui** [comment]
@Foggalong Can you make a install.sh so we can upgrade to the last update easily (the launchpad bug will last a long time  haha)

**Comment by Foggalong** [comment]
No install.sh needed, it's a really simple process. Just download the zip form [this button](https://cloud.githubusercontent.com/assets/5920259/5783776/f84d960a-9dbd-11e4-97a8-6bf673f730de.png) and then extract the contents to `~/.local/share/icons/` or `/usr/share/icons/`. Easy as pie

**Comment by dirtydancing** [comment]
Quick follow-up: For some reason, apparently `numix-icon-theme-circle` is not building daily via Launchpad PPA. I am aware that a workaround has been created, cf. https://plus.google.com/+NumixProjectOrg/posts/imqUwmCHfz3

But the last PPA update for Numix-Circle was 8 days ago, and the Files app icon is still the old one. In contrast, apparently `numix-icon-theme` is building daily via PPA, as I recently have received two updates of Numix Base via PPA with the redesigned folder icons. Current screenshot from Launchpad:

![numix_ppa](https://cloud.githubusercontent.com/assets/7164227/5991677/7237150c-a9ff-11e4-8d02-ec5928b96b80.png)

So I checked and downloaded the current `numix-icon-theme-circle-master.zip`, and with this the new `file-manager.svg` icons are showing.

**Comment by Foggalong** [comment]
Aye, the work around  means we need to trigger builds rather than them being built automatically. I'll get onto Paolo

**Comment by dirtydancing** [comment]
Just a quick reminder to trigger the PPA update for Numix-Circle on the occasion of the folder redesign.

Specifically as to the new Nautilus/Files App icon, this basic icon (so far only available via manual download) makes a noticeable visual difference in the new version that corresponds to the new folders.

**Comment by PaoloRotolo** [comment]
Hi @dirtydancing, thanks for your reminder. I've just uploaded GH sources on Launchpad and triggered a new build. You can see the status here: https://code.launchpad.net/~paolorotolo/+recipe/numix-icon-theme-circle-daily

**Comment by dirtydancing** [comment]
@PaoloRotolo Thanks! I have just re-installed Numix Circle via PPA, and everything worked just fine.

**Comment by PaoloRotolo** [comment]
Great, I'm going to close the issue.

Thank you!
