### ISSUE TITLE
Civ 5 Icon Not Showing

### ISSUE THREAD

**Issue by Arucarn** [numixproject/numix-icon-theme-circle#1424]
I have Civ 5 installed through Steam however the Numix Circle icon does not appear. I have checked and there is an icon for Civ 5 in the circle theme. Maybe the AppID has changed?

**Comment by Foggalong** [comment]
Thanks for bringing this to our attention! I have Civ5 so I'll check first thing this afternoon

On 1 January 2015 12:40:16 GMT+00:00, Oliver Warner <notifications@github.com> wrote:
>I have Civ 5 installed through Steam however the Numix Circle icon does
>not appear. I have checked and there is an icon for Civ 5 in the circle
>theme. Maybe the AppID has changed?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/numixproject/numix-icon-theme-circle/issues/1424

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Foggalong** [comment]
My guess is that you're just seeing the circle Steam icon like this. 
![screenshot - 010115 - 13 45 49](https://cloud.githubusercontent.com/assets/5920259/5592260/88af5de0-91bc-11e4-9c1f-2181102b1621.png)

That's because the Civ developers decided not to give the games launcher a specific icon, and instead set the icon line to `steam`. This is a kind of hardcoded icon, though not one made through following bad practices. If you look in the hardcoded section of the readme you'll see a possible solution to the problem.

**Comment by Arucarn** [comment]
Thanks :)

**Comment by Foggalong** [comment]
No problem!
