### ISSUE TITLE
Icon for Fritzing

### ISSUE THREAD

**Issue by l0okme** [numixproject/numix-icon-theme-circle#1478]
An icon for "Fritzing" is missing. The .desktop icon line is just `fritzing`.
The software can be found [here](http://fritzing.org/home/).
![fritzing](https://cloud.githubusercontent.com/assets/6469566/5858116/0253c812-a251-11e4-9e4c-782dc76322f2.png)

**Comment by palob** [comment]
There is an icon. It's hardcoded though. To fix it run the hardcode-fixer script:
https://github.com/Foggalong/hardcode-fixer/wiki/App-Support

Are you using the Numix-Circle PPA? I've made the icons roughly two months ago and as far as I know the PPA hasn't been updated since.
In order to update the icn theme manually click *Download ZIP* on the frontpage and extract it to where your Numix Circle theme is stored (in */usr/share/icons* , *~/.local/share/icons* or *~/.icons* probably)

**Comment by dirtydancing** [comment]
The original Numix-Circle Fritzing icon thread is here: https://github.com/numixproject/numix-icon-theme-circle/issues/1097

I just checked with current Xubuntu 14.10:

The icon line for Fritzing current version 0.9.1b (direct download) is:
`Icon=fritzing`

The icon line for Fritzing version 0.8.7b (Ubuntu Software Center) is:
`Icon=fritzing_icon.png`
