### ISSUE TITLE
"square"-background in unity launcher

### ISSUE THREAD

**Issue by alfredvaa** [numixproject/numix-icon-theme-circle#1560]
I just installed the numix-icon-theme-circle pack and in the unity launcher I still get the original squared background. According to screenshots I assumed that there should just be circle icons and that they should not be wrapped in squares...

Using Ubuntu 14.10 and unity tweak tool.
![skarmbild fran 2015-02-07 01 40 04](https://cloud.githubusercontent.com/assets/10890307/6089884/7d2db802-ae6a-11e4-8708-62ab4f39684c.png)

**Comment by dirtydancing** [comment]
1. The circle icons in your screenshot are still wrapped in squared boxes because this is a matter of the GTK theme, not of the icon theme. To just have plain circles, you will need to select Numix GTK theme instead of the Ubuntu default Ambiance GTK theme (possible via Unity Tweak Tool).

2. The Unity launcher icon itself is hardcoded and has to be changed manually. Please cf. this older post (including the CAUTION) as to how to do it: https://plus.google.com/+NumixProjectOrg/posts/fPv7DX3ErYM The current `launcher_bfb.png` icons are located in the Numix-Circle icon pack.

**Comment by alfredvaa** [comment]
I see, it works now, thanks!
