### ISSUE TITLE
Icons for avahi-ssh, avahi-vnc, avahi-zeroconf

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1711]
The original .desktop files of avahi's apps uses: ``Icon=network-wired``

But it's not possible to use it for avahi because it affect others apps too.
So I'll implement in some way the avahi desktop files inside hardcode-fixer to fix it.

Here 3 avahi icon request (or maybe symlink if you guys want):

**1** - Avahi Zeroconf Browser:
```
[Desktop Entry]
Version=1.0
Name=Avahi Zeroconf Browser
Comment=Browse for Zeroconf services available on your network
Exec=/usr/bin/avahi-discover
Terminal=false
Type=Application
Icon=network-wired
Categories=GNOME;System;
StartupNotify=false
GenericName=
```
Suggested icon name: ``avahi-zeroconf``

**2** - Avahi SSH Server Browser
```
[Desktop Entry]
Version=1.0
Name=Avahi SSH Server Browser
Comment=Browse for Zeroconf-enabled SSH Servers
Exec=/usr/bin/bssh
Terminal=false
Type=Application
Icon=network-wired
Categories=GNOME;Network;
StartupNotify=false
GenericName=
```
Suggested icon name: ``avahi-ssh``

**3**- Avahi VNC Server Browser
```
[Desktop Entry]
Version=1.0
Name=Avahi VNC Server Browser
Comment=Browse for Zeroconf-enabled VNC Servers
Exec=/usr/bin/bvnc
Terminal=false
Type=Application
Icon=network-wired
Categories=GNOME;Network;
StartupNotify=false
GenericName=
```
Suggested icon name: ``avahi-vnc``

**Comment by Foggalong** [comment]
You'd be much reporting the issue to avahi developers rather than to us. There are quite a few programs that don't hardcode their icons but instead pull a standard icon from elsewhere in the theme, be it a mimetype, a settin, category, status icon, etc. A good example that gets reported a lot is gdebi which used the .deb mime.

Anyway, because there are so many of them and it's the developers design decision (rather than not following Linux protocols as is with hardcoded icons) we have the policy of not fulfilling requests for these icons. Sorry :( if you can convince the developer to change their icon name though we'd be mor Ethan happy to oblige!
