### ISSUE TITLE
Cinnamon Control Center using wrong System Info icon

### ISSUE THREAD

**Issue by MrBaNkS** [numixproject/numix-icon-theme-circle#1856]
![screenshot from 2015-04-06 09-19-28](https://cloud.githubusercontent.com/assets/3435466/7005544/6a6d82ea-dc3e-11e4-8198-099f023a583c.png)

I think this commit: https://github.com/numixproject/numix-icon-theme-circle/commit/df3545fda6842a5372de34ccc04c0aeaf7c92fd0 broke the System Info icon in the Cinnanon Control Center. The new icon is from the Numix base icon theme I believe.

**Comment by Foggalong** [comment]
@MrBaNkS to test whether this is the case can you go into your `Numix-Circle/48x48/apps/` directory and copy `2048.svg` to `gtk-info.svg` then send a screenshot of what the control centre looks like?

**Comment by Foggalong** [comment]
@sergioad you use Cinnamon too right? Can you confirm this issue?

**Comment by MrBaNkS** [comment]
@Foggalong 

![screenshot from 2015-04-06 10-34-25](https://cloud.githubusercontent.com/assets/3435466/7006677/a11a67a4-dc48-11e4-89e8-61a6c3a91b60.png)

**Comment by Foggalong** [comment]
Ah damn :( I don't know if we can fix this because the icon name they've chosen clashes with an icon that is traditionally supposed to be in the base theme rather than an app icon. If we do fix it it causes it to pop up places where it shouldn't.

That said, the icon still shouldn't be showing up as that question mark I don't think, it should be showing a blue 'i'. If you could report that problem to [the base theme](https://github.com/numixproject/numix-icon-theme) and we'll try and fix it over there.

However, if you want the icon to be consistent you'll have to report it to the Cinnamon devs to get them to give it a unique icon name. Changing it from `gtk-info.svg` to `cs-system-info.svg` would be the recommendation as that'd make it consistent with the rest of their chosen names.
![screenshot - 060415 - 16 43 34](https://cloud.githubusercontent.com/assets/5920259/7006831/1ab0f67c-dc7c-11e4-994c-cf6443007f25.png)

@clefebvre, would you know which repo to direct this to?

**Comment by MrBaNkS** [comment]
@Foggalong Not a big deal. :) I made a symlink from info.svg to gtk-info.svg. Works for me. Ahh the power of the command line.

**Comment by Foggalong** [comment]
@MrBaNkS True also, if the symlink being there isn't causing problems for you adding it back in is fine :)

**Comment by MrBaNkS** [comment]
@Foggalong 
![screenshot from 2015-04-06 11-11-25](https://cloud.githubusercontent.com/assets/3435466/7007264/c6ebc64e-dc4d-11e4-8a8b-2f5e4a21ad77.png)

Not causing any issues for me. :)
