### ISSUE TITLE
Icon for OpenRCT2

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1926]
Game: **OpenRCT2**
Website: https://github.com/IntelOrca/OpenRCT2
Description: **Open source clone of RollerCoaster Tycoon 2**
Icon:
![image](https://cloud.githubusercontent.com/assets/11244067/7093553/9e805850-df90-11e4-9493-bbbf40472b71.png)

openrct2.desktop:
```
[Desktop Entry]
Type=Application
Version=1.0
Name=OpenRCT2
Comment=Open-source clone of RollerCoaster Tycoon 2
Exec=openrct2
Icon=openrct2
Terminal=false
Categories=Game;
```

**Comment by janisozaur** [comment]
Hi, one of openrct2 devs here.

I assume our official icon got rejected because it was not a circular one?

In case someone wants to "fix" that, here's a link to our icon in vector format: https://github.com/OpenRCT2/OpenRCT2/blob/develop/resources/logo/icon_flag.svg (there's also `noflag` version) and the discussion that was had when it was designed: https://github.com/OpenRCT2/OpenRCT2/issues/750

**Comment by Foggalong** [comment]
I'm not sure what you mean by rejected? This is an icon theme, so the idea is we redesign every icon so that the design scheme they follow is consistent for the user.
