### ISSUE TITLE
Icon for Firefox Developer Edition

### ISSUE THREAD

**Issue by jags9415** [numixproject/numix-icon-theme-circle#2012]
**Description:** Icon for Firefox Developer Edition.
**Website:** [https://www.mozilla.org/en-US/firefox/developer/](https://www.mozilla.org/en-US/firefox/developer/)

```
[Desktop Entry]
Name=Firefox Developer 
GenericName=Firefox Developer Edition
Exec=/opt/firefox_dev/firefox
Terminal=false
Icon=/opt/firefox_dev/browser/icons/mozicon128.png
Type=Application
Categories=Application;Network;X-Developer;
Comment=Firefox Developer Edition Web Browser.
```

**Icon:**
![mozicon128](https://cloud.githubusercontent.com/assets/3059433/7221234/30aa6a8e-e6a0-11e4-9b4a-8fe91264670d.png)

**Comment by wa4557** [comment]
There is one it's just hardcoded. You have to change the icon line to ` firefox-developer-icon`

**Comment by bil-elmoussaoui** [comment]
Already fixed. Please update to the last version(github version) the ppa version has not been updated in a while(until some issues get fixed)

**Comment by dirtydancing** [comment]
@jags9415 To avoid getting 3 comments telling you that this icon already exists :), it is always recommendable to search the repository before reporting a missing icon. "firefox developer" would have led you to https://github.com/numixproject/numix-icon-theme-circle/issues/1261, of which this issue is a duplicate.
