### ISSUE TITLE
Icon for Browser

### ISSUE THREAD

**Issue by togruta** [numixproject/numix-icon-theme-circle#2032]
Requesting an icon for Browser.

Icon=/usr/share/webbrowser-app/webbrowser-app.png

![screenshot from 2015-04-27 17 29 23](https://cloud.githubusercontent.com/assets/12047991/7359354/f9f6873e-ed02-11e4-9507-3c6b6d0197f3.png)

"A lightweight web browser tailored for Ubuntu, based on the Oxide browser engine and using the Ubuntu UI components."

(Apologies, I use Numix Flat Dark due to eye issues and it really lightens the Software Center)

**Comment by palob** [comment]
Hi, the latest git version has got the icon:)
I take it you're on the PPA version which hasn't received an update in a few months.
In order to get the icon right now you would have to update manaully. 
Download the latest git version via the *Download ZIP* button or using the ``git clone`` command and move the folders ``Numix-Circle`` and ``Numix-Circle-Light`` to ``/usr/share/icons`` or where your Numix Circle theme installed.

As the icon path is *hardcoded* you need to run the hardcode-fixer script (link on the frontpage).

**Comment by palob** [comment]
Ah well, you can just edit the *.desktop* file to ``Icon=web-browser`` now. It's the same icon anyway.

**Comment by Foggalong** [comment]
Just for reference the PPA is only on hold until we sort out the status icon bug. Once we have a fix for that released we'll hopefully be back on daily releases :)

**Comment by togruta** [comment]
Good to know, Foggalong. I thought I was losing my hold on reality for a bit, since the Numix Circle PPA updated for me a couple of days ago.

Ended up using Menu Libre to recode Browser to webbrowser-app, and manually updated Numix Circle and Numix Circle Light.

Thanks, you two!
