### ISSUE TITLE
Fully charged/charging battery icons look odd

### ISSUE THREAD

**Issue by TheBlackViper1996** [numixproject/numix-icon-theme-circle#2047]
The icons for when the battery is charging/fully charged look odd when compared to the other icons in the system tray, they are far too tall and fill up the entire height of the system tray whereas the other icons do not.
this happens in both Ubuntu and Elementary OS but not in other icon themes.

![numix](https://cloud.githubusercontent.com/assets/11857270/7426535/4fb1583e-efbf-11e4-8281-89786e8fa6ae.png)
![numix charging](https://cloud.githubusercontent.com/assets/11857270/7426552/ee90331c-efbf-11e4-9013-38751d382ab4.png)

The discharging/draining icons look fine.
![numix discharging](https://cloud.githubusercontent.com/assets/11857270/7426580/648651be-efc0-11e4-96a8-83ca2077bdbe.png)

**Comment by dirtydancing** [comment]
Hi there, first off, this is not an issue for Numix-Circle, but for Numix base. Anyways, some quick thoughts:

1) Which Ubuntu version is this, and on which version of elementary OS does this happen? I cannot reproduce this on Ubuntu 14.10, at least with the default settings.

2) Is it possible that you are using display scaling in Ubuntu? Please try to set to scaling factor "1" and see what happens.

3) In case of Ubuntu display scaling, the relevant icon `battery-full-charged-symbolic.svg` apparently is taken from the `scalable/status` directory, whereas Ubuntu usually is using `battery-full-charged-symbolic.svg` from the `22x22/status` directory. Please try and remove/rename `battery-full-charged-symbolic.svg` from `scalable/status` and see what happens. The same would apply to the charging icons.

4) The discharging icon is fine because in this case that one is not "symbolic"-named. The aspect that on your machine also the charging icon is "big" to me indicates that you are running Ubuntu 14.04 LTS (?).

5) For more details cf. also https://github.com/numixproject/numix-icon-theme/issues/107 and specifically https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-65576033. The best way to address this specific issue might be to remove/rename all the (12) "battery-"-named icons from `scalable/status`.

**Comment by TheBlackViper1996** [comment]
I have encountered this issue on Ubuntu 14.04.2 LTS and Elementary OS 0.2 Luna

**Comment by dirtydancing** [comment]
I see. If this is still an issue for you, as the battery icons do not belong to Numix-Circle, but rather to Numix base, please open this as a new issue in Numix base, https://github.com/numixproject/numix-icon-theme/issues.
