### ISSUE TITLE
the proposal

### ISSUE THREAD

**Issue by petrowmaxic** [numixproject/numix-icon-theme-circle#2413]
please add some icons:
viber
transmission remote (transmission-remote-gtk)
teamviewer
xdiagnose
web.whatsapp.com (webapp)

thank))

**Comment by palob** [comment]
We've got most of them, they're [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons) however. To fix this you can edit the ``.desktop`` launcher files manually or run the [hardcode-fixer](https://github.com/Foggalong/hardcode-fixer) script.

Please add the [information asked for](https://github.com/numixproject/numix-icon-theme-circle#icon-requests) to your request. Otherwise the icons cant be done.
