### ISSUE TITLE
My missing icons

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2473]
Hi, I created *temporary* icons for my icon requests! They are not perfect as you make, but they are good for me by now.

They are:
- folder-remote.svg
- gerbv.svg
- google2ubuntu.svg
- gSTM.svg
- gtkterm.svg
- gv.svg
- jstest-gtk.svg
- klayout.svg
- ms_calendar.svg
- ms_excel.svg
- ms_onedrive.svg
- ms_onenote.svg
- ms_outlook.svg
- ms_people.svg
- ms_powerpoint.svg
- ms_word.svg
- NoMachine-icon.svg
- qtsixa.svg
- receitanet-ajuda.svg
- receitanet.svg
- selektoricon.svg
- tor-browser-en.svg
- viva.svg
- winusb.svg

They can be found on my [dropbox](https://www.dropbox.com/sh/bsrnluohygrbblo/AAB_XeKvdigSxCm9ERwVJZv0a?dl=0)

There is a script to update the icons ```update-icons.sh```
It will copy the icons the icons folder and will apply the ```hardcode-fixer-mod/fix.sh``` to replace the hardcode icons. This is a temporarily modified hardcode-fixer until they don't update the repository.

*Note*: Updated with new 12 icons.

**Comment by Foggalong** [comment]
I'll have a look at these when I'm back from holiday and see if any are ready for merging :)

**Comment by leoheck** [comment]
Cool :) , however I made them quickly. The old icons were annoying me.

**Comment by Foggalong** [comment]
Back from holiday and just been taking a look at these.

There are a few on your list which we already have icons for just by another name. I'd recommend that you switch to those icon names rather than making icons with new names.

* `folder-remote` is `shares`
* `ms_excel` is `ms-excel`
* `ms_onedrive` is `onedrive`
* `ms_onenote` is `ms-onenote`
* `ms_outlook` is `web-outlook`
* `ms_powerpoint` is `ms-powerpoint`
* `ms_word` is `ms-word`
* `selektoricon` is `????` (we have one, but can't remember the name)
* `tor-browser-en` is `tor-browser-en`

A few icons just require a recolour of some existing icons. I've taken care of these in [this commit](URLGOESHERE) so you don't need to worry about that.

* `google2ubuntu` as `gnome-sound-recorder`
* `gSTM as `lock`
* `ms_calendar` as `calendar-blue-*`
* `ms_people` as `addressbook`
* `winusb` as `web-microsoft`

That leaves the following which need to be added from fresh. A lot of your icons are good starts but need modification to adhere to the Numix design guidelines a bit closer.

* `gerbv`
* `gtkterm`
* `gv`
* `jstest-gtk`
* `klayout`
* `NoMachine-icon`
* `qtsixa`
* `receitanet-ajuda`
* `receitanet`
* `viva`

I can either do that for you or you can do it and then submit via pull request. Which way we do it is entirely up to you :)

**Comment by Foggalong** [comment]
As a bonus I've also added ms-calendar to the [dynamic calendar icons](https://github.com/numixproject/numix-calendar-icons) script so that you can use that with it too :)

**Comment by leoheck** [comment]
Awesome!!

**Comment by Foggalong** [comment]
So would you like to do them or do you want me to?

**Comment by leoheck** [comment]
Oh, I didn't saw [this](https://github.com/numixproject/numix-icon-theme-circle/issues/2473#issuecomment-131554997) answer. Sure, I can do it!

**Comment by Foggalong** [comment]
Sure thing! Set up 10 pull requests then, one for each of the additions needed and we'll set about working them to be closer to the guidelines :)

**Comment by leoheck** [comment]
@Foggalong, Can I upload all the modifications at once? Why do you ask me to make 10 pull requests?
By now I changed these icons to the name you suggest:

```
Application        , (...)
Google2Ubuntu      ,
Google2Ubuntu      ,
MS Calendar        ,
MS Excel           ,
MS Onedrive        ,
MS Onenote         ,
MS Outlook         ,
MS People          ,
MS Powerpoint      ,
MS Word            ,
SelekTOR           ,
SSH Tunnel Manager ,
Tor Browser        ,
WinUSB             ,
```

**Comment by Foggalong** [comment]
10 separate pull requests is easier on our side since it means we can merge in individual icons as soon as they're ready rather than waiting for all 10.

If you'd prefer you can submit all 10 in 1 but it'll just be longer before any of them make it in

**Comment by leoheck** [comment]
- ```selektoricon is also selektoricon```

**Comment by leoheck** [comment]
@Foggalong, can you work on the missing icons? As you said, I created just to use as starting point. I will update the hardcode-fixer paths that already have icons.

- gerbv
- gtkterm
- gv
- jstest-gtk
- klayout
- NoMachine-icon
- qtsixa
- receitanet-ajuda
- receitanet 
- viva ([Cadence Viva Waveform Viwer](http://community.cadence.com/CSSharedFiles/blogs/cic/Stacy_Whiteman/vivamarker.jpg) doesn't have an icon)

**Comment by Foggalong** [comment]
Sure thing! :D

**Comment by leoheck** [comment]
@Foggalong, viva icon can be like gtkwave as it has the same functionality.
