### ISSUE TITLE
Monochrome icon style not respected for indicators

### ISSUE THREAD

**Issue by keunes** [numixproject/numix-icon-theme-circle#2609]
Standard, all indicators are monochrome. With the update of two days ago, the [caffeine](https://launchpad.net/caffeine) and the bluetooth icons became coloured. Personally I don't like it that much, but more importantly this renders a problem when the Dash is pulled forward, as the icons become plain circles:
![screenshot from 2015-10-14 14 31 22](https://cloud.githubusercontent.com/assets/11229646/10483766/5b20171a-7281-11e5-9520-c6c72cf60545.png) [normal]
![screenshot from 2015-10-14 14 32 42](https://cloud.githubusercontent.com/assets/11229646/10483767/5b224f26-7281-11e5-9da1-ddea9e3f07dd.png) [with dash open]

**Comment by dirtydancing** [comment]
This is a duplicate of https://github.com/numixproject/numix-icon-theme-circle/issues/2602 and https://github.com/numixproject/numix-icon-theme-circle/issues/2601. Basically, this is fixed in git, but the fix has not landed in the Numix-Circle PPA yet. The next automated PPA update might be a little while because of https://github.com/numixproject/numix-icon-theme-circle/issues/2430.

As to the Ubuntu/Unity panel displaying plain white circles for Numix-Circle icons in the panel when Dash is opened: I believe that is Ubuntu/Unity behaviour and cannot be addressed from Numix's side.

**Comment by keunes** [comment]
Well, in my view this is certainly not a dupe of #2602: that one covers the very concrete issue of broken active/passive status of an icon, whilst my point here is that the whole *concept* of introducing colour to indicators is 'wrong' (can't find a better word, sorry).

In any case, although I first thought #2601 was a different issue as the OP mentioned the circle icon being chopped off, the discussion there has developed to cover the concept of a circle background and colour, indeed :)
It's been a bit difficult to get a picture as there appear to be many similar bug reports (including #2274 and https://github.com/numixproject/numix-icon-theme/issues/779). But if I understand you correctly, in git the indicators were reverted back to using monochrome icons with transparent backgrounds?

Regarding the 'white circles' in the panel when the Dash is opened: Not sure whether to continue this here (or I should introduce it in #2601) and whether it even is still relevant after the update that still has to land in the PPA. But I just wanted to note that even if this is Ubuntu/Unity behaviour, it is Numix that introduced the opaque circle background where previously there was transparency around the monochrome icons ;)

**Comment by keunes** [comment]
Ok, just saw your comment in #2430 :+1:
I understand that indeed the icons are going back to monochrome ones, once symlinks have been restored in the PPA :)

**Comment by dirtydancing** [comment]
No worries about duplicate or not-duplicate, I agree that this is a somewhat confusing situation, and reporting in case of doubt is always a good thing and appreciated.

To clarify: I am not aware that there is a concept of introducing colour to the indicator icons. This has just happened because cross-repo folder symlinks have broken. For more background, just in case of interest, there is the long long issue thread over at https://github.com/numixproject/numix-icon-theme/issues/190.

And yes, this issue has been fixed already in git.

The issue regarding the panel when Dash is opened is a direct consequence of Numix-Circle coloured icons being (wrongly) displayed in the panel, and will be fixed once the monochrome icons are displayed again.

Hope this clarifies things. Please do not hesitate to ask/report in case of any doubts.

**Comment by keunes** [comment]
Thanks :+1:

**Comment by dirtydancing** [comment]
Ah, cross-posted at the same time :) And thanks to you as well :+1:
