### ISSUE TITLE
404 - Not found

### ISSUE THREAD

**Issue by Th3f** [numixproject/numix-icon-theme-circle#3016]
When I wanted to install numix-icon-theme-circle from your ppa on Debian with Gnome 3, I got a 404 - Not found: http://ppa.launchpad.net/numix/ppa/ubuntu/dists/jessie/main/binary-amd64/Packages

**Comment by gregorydk** [comment]
Because Jessie doesn't exist. Use Xenial.

http://ppa.launchpad.net/numix/ppa/ubuntu/dists/xenial/main/binary-amd64/

**Comment by Th3f** [comment]
Ah, okay... Didn't know this. Thanks!

**Comment by Foggalong** [comment]
Someone else asked about adding Debian support in our PPAs a while back - was that you? I didn't even realise this was possible or how I'd go about enabling such a thing.

**Comment by Th3f** [comment]
Nope, that wasn't me, but It would be cool.

**Comment by gregorydk** [comment]
@Foggalong 

Since you have no dependencies, your repo is compatible with Debian. You could change the naming though.

Now you have:
`deb http://ppa.launchpad.net/numix/ppa/ubuntu YOUR_UBUNTU_VERSION_HERE main`

For Debian you need:
`deb http://ppa.launchpad.net/numix/ppa/debian unstable main`
or
`deb http://numixproject.org/numix/debian unstable main`

**Comment by gregorydk** [comment]
You can use Aptly for it. https://www.aptly.info/
