### ISSUE TITLE
Files icon not circled

### ISSUE THREAD

**Issue by orschiro** [numixproject/numix-icon-theme-circle#78]
The icon for the file manager is not circled. Tested on Linux Mint 18.3 Cinnamon.

![image](https://user-images.githubusercontent.com/170947/34866662-96b12ea8-f77d-11e7-9793-6251043647b2.png)

**Comment by bil-elmoussaoui** [comment]
It's just the file manager you use doesn't use the correct icon. I hate cinnamon just because they don't respect the FreeDesktop standards. They're using an icon from the `Places` context instead of the `Applications` context. See here for more information https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

**Comment by orschiro** [comment]
Should I report this against Nemo file manager, thus?

**Comment by bil-elmoussaoui** [comment]
Yeah 👍
