### ISSUE TITLE
Please update AUR

### ISSUE THREAD

**Issue by Oslint** [numixproject/numix-icon-theme-circle#97]

**Comment by palob** [comment]
It is really annoying when a package is not updated. Yet the AUR maintainer is none of our guys and [https://aur.archlinux.org/packages/numix-circle-icon-theme-git](reading his comment) he takes issue with our versioning scheme.

Would be nice to get into the community repo like Papirus.

**Comment by Foggalong** [comment]
I realise that date based versioning isn't for everyone (even though it's increasingly becoming the standard) but what a ridiculous hill to die on.

*I don't like the versioning scheme which this software uses so rather than adopt it or even modify it to a different one locally I'm going to completely abandon the package which 1000s of people use.*

**Comment by palob** [comment]
As far as I can see the (AUR package)[https://aur.archlinux.org/packages/numix-circle-icon-theme-git] stopped updating again.

From the comments relating to the AUR VCS policies I can only infer we'd have to additionally push out releases on GitHub instead of just tagging (which is one more click to do) but we didn't do this in the past and the (Square package)[https://aur.archlinux.org/packages/numix-square-icon-theme/] is up-to-date nontheless.

@Stunkymonkey, are you by any chance the *Stunkymonkey* denoted as ``numix-circle-icon-theme-git`` package maintainer? Do you still maintain the AUR package?

**Comment by Stunkymonkey** [comment]
Yes I maintain it.
When compiling the package the resulting package version (is not necessarily equivalent to the aur-website) get updated to the latest tag of the repository. The version number is fetched from the tag. This behavior is normal and wanted for `*-git` packages.

Pro: nothing to do for me when an update happens.
Con: the version on the aur-website does not reflect the correct package version.
Fix: Create a non`-git` package with a fixed version number.

I could update the version numbers by hand. Other then the website there is no difference. Every user will automatically install the latest version.

Compiling the `PKGBUILD`s the following packages are produced:
- `numix-icon-theme-git-21.10.31.r0.g7a28092dd-1`
- `numix-circle-icon-theme-git-21.10.31.r0.gfccd3b9-1`

**Comment by palob** [comment]
Thank you, so the users flagging out-of-date just aren't triggering the update?

**Comment by Stunkymonkey** [comment]
flagging "out-of-date" sends an email to me.
But just by adding a new tag everybody will receive the update by calling `yay -Syua`. Even without me doing anything.
I can update it (I will later), but is it just more work without a big advantage.

**Comment by Stunkymonkey** [comment]
surely for maintainer this is not optimal (to not know what version is available).

**Comment by Stunkymonkey** [comment]
i just updated the version numbers. :tada:

**Comment by palob** [comment]
I guess there is no need to do that in future, thank you for the maintenance :heart:
