### ISSUE TITLE
KMail (Other clients?) - Different mail statuses and folder icons have the same icon

### ISSUE THREAD

**Issue by ozone89** [numixproject/numix-icon-theme-circle#983]
First picture shows a conversation where I have sent and replied to a mail
default oxygen theme for comparison

![paste61](https://cloud.githubusercontent.com/assets/7688273/3635619/c35248fe-0f80-11e4-8c7a-f613492ebe48.png)
![paste62](https://cloud.githubusercontent.com/assets/7688273/3635620/c356abd8-0f80-11e4-94ef-fef8eee37323.png)

same goes with other status icons, like in the folder view:

![paste63](https://cloud.githubusercontent.com/assets/7688273/3635625/11feefca-0f81-11e4-8aab-168d40710538.png)
![paste64](https://cloud.githubusercontent.com/assets/7688273/3635626/12052bec-0f81-11e4-8a39-d062c30beea4.png)

also, looks like some icons are missing, leaving the emblem alone, like the drafts and models ones

**Comment by Foggalong** [comment]
These are all the icons which use that mail icon. I can't see just looking at them which would be causing this problem though :/

```
./pop3.svg
./internet_mail.svg
./imap.svg
./mail.svg
./kmailcvt.svg
./email.svg
./xfce-mail.svg
./package_internet_email.svg
./e-mail.svg
./kmail2.svg
./preferences-mail.svg
./internet-mail.svg
./mail-generic.svg
./redhat-email.svg
./mail_generic.svg
./sylpheed.svg
./x-office-mail.svg
./email-client.svg
./xfce-newmail.svg
```

**Comment by wa4557** [comment]
it's possible that this happens because the icons `mail-folder-inbox.png`   `mail-folder-sent.png`
`mail-folder-outbox.png`  `mail-message.png` are not present in Numix, and therefore the numix-circle icon `kmail` is used. At least the corresponding icons from the oxygen theme do have this name

**Comment by Foggalong** [comment]
Huh, so if kmail2 is removed those icons don't show? O.o

**Comment by wa4557** [comment]
No idea (and frankly I don't want to install a kde-application on my unity-machine :) but since the other icons are shown, I suppose that the better way to solve this is to add the appropriate `places` `mail` icons :)

**Comment by Foggalong** [comment]
Yeah same on my XFCE machine. Them dependencies are just not worth it :P I might see if I can get a KDE VM setup though

![screenshot - 060415 - 17 14 53](https://cloud.githubusercontent.com/assets/5920259/7007306/7bfdc58c-dc80-11e4-8f1b-a45183658f70.png)

**Comment by dirtydancing** [comment]
For what it is worth: I had no problem installing KMail on Ubuntu 14.10 (already using e.g. Okular): Well, at least in Ubuntu 14.10, with current Numix-Circle and Numix via GitHub, the KMail window looks like this (KMail 4.14.1, KDE 4.14.1), apparently non-themeable icons are used:

![kmail_ubuntu14 10](https://cloud.githubusercontent.com/assets/7164227/7009128/5a95212a-dc98-11e4-93ad-b2d8e73bab74.png)

**Comment by wa4557** [comment]
Seeing this screenshot I remebered why I prefer gnome apps :P

**Comment by Foggalong** [comment]
I'll confess, I really love Plasma 5 and it's the first DE in a while that's possibly been able to tempt me away from XFCE in a long time.

Anyways, I was able to replicate the bug to some extent (not sure why you couldn't @dirtydancing). Deleting `kmail2.svg` had no effect on this however, so I'm guessing the problem lies with one of the other icons listed.
![screenshot - 060415 - 19 36 07](https://cloud.githubusercontent.com/assets/5920259/7009765/7f50ec96-dc94-11e4-9a62-8c4ef62e3817.png)

**Comment by wa4557** [comment]
@Foggalong have you tried adding one of the missing mail icons? I still think that causes it....

**Comment by Foggalong** [comment]
I haven't yet, but it still must be picking the replacement icon from somewhere. At this point I'm just curious as to know which it is :P

**Comment by Foggalong** [comment]
@wa4557 creating those missing icons doesn't fix it either :/

**Comment by wa4557** [comment]
Well then I'm officially out of Ideas :/ why does it pick those icons from oxygen but not numix?

**Comment by wa4557** [comment]
@Foggalong The replacement icon is most definitely `kmailcvt.svg` (because that's apart from `kmail2.svg` the other additional icon the kmail package installs) + the "New" icon (the most left) in your screenshot has to be `mail-message-new` (that's the icon in the oxygen theme that looks exactly like the one from @dirtydancing s screenshot) which is strangely enough available in Numix but appearently doesn't get picked o.O

**Comment by bil-elmoussaoui** [comment]
I don't really know how this works. In eOS ferya beta 2 with geary using Numix-Circle with elementary base icon theme. There's an icon that took the circle icon instead of the normal icon from the elementary base theme. It's might not be the same app but if we found out how to solve this for Kmail, the same solution would work for Geary too
![screenshot from 2015-04-06 22 35 21](https://cloud.githubusercontent.com/assets/7660997/7011884/420fa80e-dcad-11e4-90a0-2f329a10ad42.png)

**Comment by wa4557** [comment]
@bil-elmoussaoui Is geary a qt-app? If yes then it might be similar indeed
@dirtydancing If you want to theme kde applications in Ubuntu (might be interesting for you if you use okular) you have to install `systemsettings` and change your icon theme to Numix there as well, by doing so you should also be able to theme kmail.

![bildschirmfoto vom 2015-04-06 22 50 35](https://cloud.githubusercontent.com/assets/6475757/7012331/c6979cc8-dcb0-11e4-8d78-9c6d9d255500.png)
![bildschirmfoto vom 2015-04-06 22 54 29](https://cloud.githubusercontent.com/assets/6475757/7012330/c695e7a2-dcb0-11e4-9c38-7989835d368f.png)

@Foggalong I figured it out (I think) I installted kmail on my Ubuntu machine and saw that a lot of the icons are indeed missing (first screenshot). But after adding `mail-receive.svg` (2nd screenshot symlink to `gtk-copy`) the icon changed to the right one. This means that there are actually a lot of icons missing in Numix. Namely (excerpt)

- mail-receive
- mail-folder-sent
- mail-folder-inbox
- arrow-down-double (up, left, right)
- doument-encrypt 
- document-decrypt
...

**Comment by Foggalong** [comment]
I'll be honest, I known this is more about general icons being missing but we have pretty much KDE support. Because all our devs  use GTK environments when the theme is being made most of the work goes into them. Then, because it's got such great GTK support most our users end up using GTK environments so most the issues reported relate to them. Then, because most the issues are GTK related we put more time into them, and thus the cycle continues.

One of these days I'm gonna have to install KDE or LXQt as my daily driver so it forces me to improve the support with that side of things. I did it for a few days a while back for Circle and we got several hundred new icons just in that period. I'll have to do the same again but for base :)

**Comment by dirtydancing** [comment]
@wa4557 Thanks for pointing me to `systemsettings` (as a side note: KDE System Settings, using the icon line `preferences-system`, so no extra KDE icon for this one).

With the occasional use of Okular (which is much more powerful than e.g. Evince), so far I have not bothered with KDE theme-ing on Ubuntu.

When setting the icons to `Numix-Circle` via KDE System Settings, I can replicate the initial bug (for this one, I used the PPA version of Numix-Circle, just in case that the version should be of relevance here):

![kmail_a](https://cloud.githubusercontent.com/assets/7164227/7019561/9f132b7a-dd11-11e4-9589-d971ec98fc83.png)

@Foggalong The icon that KMail picks up appears to be `mail.svg` (symlink with the target `mail_generic.svg`). Deleting/renaming `mail.svg` in Numix-Circle leads to this result:

![kmail_b](https://cloud.githubusercontent.com/assets/7164227/7019589/d5ac83e8-dd11-11e4-900e-7f96e44188c6.png)

**Comment by Foggalong** [comment]
I'm so glad you could replicate this too. I nearly went crazy yesterday having to reboot the VM every time I deleted an icon.

**Comment by dirtydancing** [comment]
@Foggalong I guess I got lucky: `mail.svg` was the icon I checked right after the two `kmail*` ones :-)

@wa4557 Just a heads-up warning for using KDE System Settings on Ubuntu: I got my font rendering all messed up e.g. in Firefox and Thunderbird, although I only changed the icon theme for KDE apps via KDE System Settings. If that should happen to you as well: removing `~/.config/fontconfig/fonts.conf` and logging back in did the trick for me (got me back to the brilliant Ubuntu default font rendering), cf. https://askubuntu.com/questions/307462/trying-to-change-kde-setting-something-changed-the-font-font-rendering-and-i-can

**Comment by wa4557** [comment]
Ok. `mail.svg` is this used somewhere else? If not we can delete it and after adding the missing `kde` icons (or is this a wontfix?; if you declare Numix to be a gtk-icon theme) `kmail` (and possibly a lot of other `kde` applications will be themend)

@dirtydancing Thanks, but doesn't bother me because I use chromium :P

**Comment by dirtydancing** [comment]
@wa4557 Haha, as far as I understand it, if this occurs it applies to all applications, so Chromium might not save you :-)

**Comment by Foggalong** [comment]
I think we can safely delete it :)

**Comment by Foggalong** [comment]
Someone with working kmail report the missing action actions needed to base :)
